directory: /mnt/disk_angel/Musica
import:
  move: true
  log: ~/.config/beets/log.txt
ui:
  color: yes
paths:
  default: $albumartist/$original_year - $album%aunique{}/$track - $title
  comp: $albumartist/Compilations/$original_year - $album%aunique{}/$track - $title
  singleton: $artist - $title
  albumtype:soundtrack: Bandas Sonoras/$album/$track - $title
  albumtype:single: $albumartist/Singles/$original_year - $album%aunique{}/$track - $title
  albumtype:ep: $albumartist/EPs/$original_year - $album%aunique{}/$track - $title

